### PR TITLE
Correctly handle logical volume names with space in name

### PR DESCRIPTION
**Pull request by a-schild**
Fix for issue #2 under linux

### CODE REVIEW

**Review by GOID1989 — APPROVED** [review]
thanks for commit!

**Review by GOID1989 — COMMENTED** [review]
this feature out of adaptec tools functionality. I think most env-s use separated template for SMART monitoring.

**Comment by a-schild** [comment]
The smart monitoring is added here, since the detection fo the disks attached to the raid controller needs to be done via the adaptect utility

**Comment by GOID1989** [comment]
this tested only for Zabbix 4 ?

**Pull request merged**
